### ISSUE TITLE
Help: Plan My Trip Lambda Syntax Error

### ISSUE THREAD

**Issue by ipanema99** [alexa/alexa-cookbook#41]
Could someone please help me resolve a syntax error I'm getting when using the unaltered sample-nodejs-plan-my-trip src? I'm following the [cookbook instructions ](https://github.com/alexa/alexa-cookbook/blob/master/handling-responses/dialog-directive-delegate/step-by-step/2-lambda-function.md)

I get an "Execution result: failed" with following details when I press "save and test" my PlanMyTrip lambda function:

> START RequestId: c89431d8-aeb8-11e7-a28a-13650abcedf2 Version: $LATEST
Syntax error in module 'index': SyntaxError
 const speechOutput;
       ^^^^^^^^^^^^
SyntaxError: Missing initializer in const declaration
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
END RequestId: c89431d8-aeb8-11e7-a28a-13650abcedf2
REPORT RequestId: c89431d8-aeb8-11e7-a28a-13650abcedf2	Duration: 10.85 ms	Billed Duration: 100 ms 	Memory Size: 128 MB	Max Memory Used: 19 MB	

Any advice on how to address this would be MUCH appreciated! 

Thanks,

Dave
<img width="1007" alt="screen shot 2017-10-11 at 12 17 16 pm" src="https://user-images.githubusercontent.com/30736380/31462630-3a321884-ae82-11e7-8e9d-14cd5257d71e.png">
<img width="973" alt="screen shot 2017-10-11 at 12 17 26 pm" src="https://user-images.githubusercontent.com/30736380/31462640-3d598ccc-ae82-11e7-9ffb-536c06ac55c4.png">

**Comment by csosa27** [comment]
What did you use as test script (JSON arguments)?

**Comment by ipanema99** [comment]
Hi Carl – thanks for your response! 

 

Hmmm…the test script could be my issue. I’m a newbie and don’t know how to configure/use a test script. Could you point me to a a resource for learning how to set up a test script for Plan My Trip?

**Comment by SleepyDeveloper** [comment]
The problem is with the sample code. `const speechOutput;` isn't set to anything. Constants need to be assigned to a value. 

You'll need to change `reprompt` as well.

so the code should look like:

```
 let speechOutput;
 let reprompt;
```

**Comment by SleepyDeveloper** [comment]
@ipanema99 thanks for reporting this! The code has been updated. Let me know it works and I'll close this issue.

**Comment by ipanema99** [comment]
Thanks for your responsiveness -- I definitely appreciate it!

I tried the updated code – it resolves the syntax problem, but I now get a different error:

> START RequestId: 76d4fe62-aec5-11e7-a645-f9ea0f129b0e Version: $LATEST
2017-10-11T20:47:59.085Z	76d4fe62-aec5-11e7-a645-f9ea0f129b0e	TypeError: Cannot read property 'locale' of undefined
    at AlexaRequestEmitter.HandleLambdaEvent (/var/task/node_modules/alexa-sdk/lib/alexa.js:107:38)
    at AlexaRequestEmitter.value (/var/task/node_modules/alexa-sdk/lib/alexa.js:95:31)
    at exports.handler (/var/task/index.js:99:11)
END RequestId: 76d4fe62-aec5-11e7-a645-f9ea0f129b0e
REPORT RequestId: 76d4fe62-aec5-11e7-a645-f9ea0f129b0e	Duration: 131.49 ms	Billed Duration: 200 ms 	Memory Size: 128 MB	Max Memory Used: 32 MB	
RequestId: 76d4fe62-aec5-11e7-a645-f9ea0f129b0e Process exited before completing request

This error appears when both when using the code unaltered, and when replacing index.js line 32 with 
`const` APP_ID = 'amzn1.ask.skill.850dd42c-6aed-4c6f-8eea-66efff7e22b1';  // TODO replace with your app ID (OPTIONAL).

BTW, I followed the [instructions in Step 9 ](https://github.com/alexa/alexa-cookbook/blob/master/handling-responses/dialog-directive-delegate/step-by-step/2-lambda-function.md) (which are slightly outdated from current AWS UI), and have assigned a custom function role (Execution Role) rather than "lambda_basic_execution"...I believe that this is all correct, but perhaps this is part of the problem?

Any recommendations on next steps would be most appreciated.

Thanks,

Dave

<img width="1325" alt="screen shot 2017-10-11 at 1 48 45 pm" src="https://user-images.githubusercontent.com/30736380/31466352-b89ff444-ae8b-11e7-8ca8-fabbc3ef24bc.png">

**Comment by SleepyDeveloper** [comment]
@ipanema99 I am unable to replicate the error you're having. 

Two things to check out:

1.  the error message suggests that your lambda function is timing out. Under Configuration > Basic Settings try increasing the time out and see if works. 

2. When you created your lambda function, did you choose the 'fact skill blueprint'? The blueprint contains all the node.js modules that the skill needs. If you didn't you'll need to create a new lambda and select the blueprint.

**Comment by ipanema99** [comment]
Thanks for your help Justin!

I created a new Lambda function using alexa-skill-kit-sdk-factskill blueprint, and I no longer get the syntax error when simply saving the function, which is great.

I'm still unable to get the Skill to work end-to-end, however. When I try "Open Plan My Trip" on https://echosim.io, I get the response "There was a problem with the requested skills response." The developer console service simulator shows the response "The remote endpoint could not be called, or the response it returned was invalid." 

Can you suggest any next steps to try to resolve this?

(Attached screenshot shows example. I renamed the skill from "Plan my Trip" to "Get Ahead"
<img width="1248" alt="screen shot 2017-10-11 at 6 05 09 pm" src="https://user-images.githubusercontent.com/30736380/31474532-3ea5bbae-aeb0-11e7-9010-c3553658b1bb.png">
)

**Comment by SleepyDeveloper** [comment]
@ipanema99 That would indicate an error on your lambda function. You can run a test on lambda to see the error message. Copy the JSON from the "Lambda Request" box. Then go to your lambda function on AWS you should see a drop down with an orange button that says, "test" on it. Click on the dropdown and select "Configure Test Event" I modal should appear. Create a new test and paste the JSON into the editor. Click save and test and error message should appear.

**Comment by ipanema99** [comment]
Thanks Justin!

 

I found that commenting out these two lines in index.js solves the problems, and it works end to end. Thanks for all your help.

// let speechOutput; 

// let reprompt; 

 

Dave
