### ISSUE TITLE
Cannot read property 'DirectiveService' of undefined

### ISSUE THREAD

**Issue by Ashish-V** [alexa/alexa-cookbook#60]
Hello, when I am trying to call the progressive response API from the existing lambda function, I am facing this issue. 

2017-11-22T08:40:08.274Z	bebcbe7b-cf60-11e7-be8e-ed18ddd1ba6c	Unexpected exception 'TypeError: Cannot read property 'DirectiveService' of undefined':
TypeError: Cannot read property 'DirectiveService' of undefined
at Object.CardFaq (/var/task/index.js:66:38)
at emitNone (events.js:86:13)
at AlexaRequestEmitter.emit (events.js:185:7)
at AlexaRequestEmitter.EmitEvent (/var/task/node_modules/alexa-sdk/lib/alexa.js:215:10)
at AlexaRequestEmitter.ValidateRequest (/var/task/node_modules/alexa-sdk/lib/alexa.js:172:23)
at AlexaRequestEmitter.HandleLambdaEvent (/var/task/node_modules/alexa-sdk/lib/alexa.js:117:25)
at AlexaRequestEmitter.value (/var/task/node_modules/alexa-sdk/lib/alexa.js:92:31)
at exports.handler (/var/task/index.js:12:19)

**Comment by VishalRam** [comment]
Did this get resolved?

**Comment by franklin-lobb** [comment]
closing due to age. if the issue still exists, please reopen.
